name: big-file-eraser
version: "1.0.0"
summary: A simple file manager to find and delete large files.
description: |
  Big File Eraser is a lightweight file manager that helps you find and delete large files easily.

base: core22
confinement: strict
grade: stable

apps:
  big-file-eraser:
    command: python3 $SNAP/main.py  # Ensure this points to your main script

parts:
  big-file-eraser:
    plugin: python
    source: .
    python-packages:
      - PySide6
    stage-packages:  # Add required system libraries and Python interpreter
      - python3
      - python3-pip
      - libx11-6
      - libfontconfig1
      - libxkbcommon0
      - libegl1
      - libgl1
      - libpulse0
      - libxcb1
      - libxcb-dri3-0
      - libxcb-cursor0
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-render-util0
      - libxcb-render0
      - libxcb-shape0
      - libxcb-xkb1
      - libxkbcommon-x11-0
      - libwayland-cursor0
      - libwayland-egl1
      - libwayland-client0
      - libatomic1
      - libasound2
      - libnss3
      - libxrandr2
      - libxrender1
      - libxi6
      - libxtst6
      - libxcomposite1  # Corrected case
      - libxdamage1     # Corrected case
      - libxkbfile1
      - libxslt1.1
