name: big-file-eraser
version: "1.0.0"
summary: A simple file manager to find and delete large files easily.
description: |
  Big File Eraser is a lightweight file manager that helps you find and delete large files easily.

base: core22
confinement: strict
grade: stable

apps:
  big-file-eraser:
    command: python3 $SNAP/main.py
    environment:
      PYTHONPATH: $SNAP/lib/python3.10/site-packages:$SNAP/usr/lib/python3.10
      LD_LIBRARY_PATH: $SNAP/lib/python3.10/site-packages/PyQt6/Qt6/lib:$SNAP/usr/lib:$LD_LIBRARY_PATH
    plugs:
      - x11
      - opengl
      - network

parts:
  eraser:
    plugin: python
    source: .
    python-packages:
      - pandas
      - PyQt6
      - humanize
    stage-packages:
      - libglib2.0-0
      - libfontconfig1
      - libxkbcommon0
      - python3
      - qt6-base-dev
      - qt6-wayland
      - qt6-image-formats-plugins
      - libqt6gui6
      - libqt6widgets6
      - libqt6opengl6
      - libqt6printsupport6
      - libqt6quick6
      - libqt6quickcontrols2-6
      - libqt6waylandclient6
      - libxi6
      - libxrender1
      - libcairo2
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libgdk-pixbuf2.0-0
      - libxrandr2
      - libxcomposite1
      - libxdamage1
      - libatk1.0-0
      - libatk-bridge2.0-0
      - libgtk-3-0
      - libpulse0
      - libsndfile1
      - libvorbis0a
      - libvorbisenc2
      - libogg0
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/lib/python3.12/site-packages/PyQt6/Qt6/plugins/platformthemes
      cp -r .venv/lib/python3.12/site-packages/PyQt6/Qt6/plugins/platformthemes/* $CRAFT_PART_INSTALL/lib/python3.12/site-packages/PyQt6/Qt6/plugins/platformthemes/